services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: dbmaster
      POSTGRES_USER: dbmasteruser
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"